services:
  - type: web
    name: accessguard-backend
    env: python
    rootDir: accessguard_backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        value: 3306
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
    healthCheckPath: /api/health
